/*
	Moonshine
	Copyright (c) 2007-2008 Samuel Saint-Pettersen
	Released under the MIT License
	Interface definition for Moonshine Lua interpreter
*/

#include "nsISupports.idl"

[scriptable, uuid(A1091011-3C4E-47b8-B35A-B8EE21D33C81)]
interface IMoonshineLua : nsISupports {
	float Version();
};
